### ISSUE TITLE
Error: when Remove AE

### ISSUE THREAD

**Issue by rinnocenti** [mclemente/fvtt-advanced-macros#10]
![image](https://user-images.githubusercontent.com/3178127/121831801-ccee4b00-cc9e-11eb-9f61-4ba7f371b534.png)
when an effect is removed rom another actor, after the actor who applied the effect has been removed from the scene, it does not find the actor and gives this error.

**Comment by mclemente** [comment]
Could you share the effects and macro you've used? I'm not used to DAE to debug it.

**Comment by rinnocenti** [comment]
yep

[macro.zip](https://github.com/League-of-Foundry-Developers/fvtt-advanced-macros/files/6645793/macro.zip)
