### ISSUE TITLE
Request: Add identifier to allow strings with spaces to be passed as a single argument

### ISSUE THREAD

**Issue by chligget** [mclemente/fvtt-advanced-macros#47]
This would just be a nicety, but it would be a fantastic feature to pass a phrase or sentence as a single argument. There are of course ways around this so it's not a big deal, but something built-in would be great.

For example: @UUID[Macro.ID foo "This is arg2" "Hello from arg3"]{Macro}

Thank you for your consideration and efforts as a whole!

**Comment by mclemente** [comment]
Foundry V11 will overhaul how macro calls are made, so this isn't feasible anymore.
