### ISSUE TITLE
Missing versions on FoundryVTT Website

### ISSUE THREAD

**Issue by MrVauxs** [mclemente/fvtt-advanced-macros#49]
The module does not update to the newest, 1.19.1 version due to the FoundryVTT website not having it listed.
Please, update your [release.yml](https://github.com/League-of-Foundry-Developers/fvtt-advanced-macros/blob/f3cf47a666ac99485c3107e82133a07de5da42db/.github/workflows/release.yml#L74) file to do this automatically for you. You can get the new way of doing so from my modules, as an [example](https://github.com/MrVauxs/pf2e-jb2a-macros/blob/8c1e0ac2cd5ebe25685d57cc233573c3474c104a/.github/workflows/main.yml#L48)

**Comment by mclemente** [comment]
The latest version links to `releases/latest`, it doesn't need to be updated on the admin page for every single release.

**Comment by MrVauxs** [comment]
> The latest version links to `releases/latest`, it doesn't need to be updated on the admin page for every single release.

It would be beneficial given the fact that people on 1.18 are stuck there until they reinstall (because of the `v` difference) and come to other modules with issues that wouldn't exist if the module updated itself properly.

**Comment by MrVauxs** [comment]
I would make a PR to have this automated but it requires having the login credentials in your GitHub secrets.

**Comment by mclemente** [comment]
Yes, one of the issues is that this repo is the League's, not mine, but I own the package in the foundry admin page. I'll try transfering this repo to me.
