### ISSUE TITLE
/amacro is not a valid chat message command

### ISSUE THREAD

**Issue by benjamin-ping-xu** [mclemente/fvtt-advanced-macros#57]
Issue: I cannot make the example in the README work. Error message: "advanced-macros | Error: /amacro is not a valid chat message command."
My environment: I am using The Forge to host my game. Running latest 5e (2.1.4) and Foundry (v10 build 291). I have disabled all modules except: Advanced Macros, libWrapper, socketlib

Steps: I created the 'Move token', 'pan', 'current-time', 'Return to corner', and 'run' macros based on the README, and then tried to execute the 'run' macro, first by typing '/run', then clicking 'execute macro' in the window. 

Expected behavior: as described in README
Observed behavior: If called through chat, 'Error: /run is not a valid chat message command'. If manually executed, "advanced-macros | Error: /amacro is not a valid chat message command."

I'm sure I'm just an idiot and I'm doing something wrong but I can't figure out why it's not working. Thanks!

**Comment by mclemente** [comment]
You're not dumb. The README was made for 1.19, and that was a new feature, but the module went through a lot of fixes due to the breaking changes between 1.18 and 1.19, and that feature probably got broken with the fixes.

I'll try to get it fixed. Worst case scenario would be to change the README to not be misleading.

**Comment by mclemente** [comment]
Hello, the latest version (1.19.5) fixed some of those issues. There are still some issues to be fixed, but just calling "/amacro" shouldn't throw an error anymore.

**Comment by mclemente** [comment]
Foundry V11 will overhaul how macro calls are made, so the `/amacro` call will be removed. This time around, the README will be up to date.
