### ISSUE TITLE
Executed macros return undefined

### ISSUE THREAD

**Issue by Cuingamehtar** [mclemente/fvtt-advanced-macros#58]
Hello.
Foundry version: v10.291
AM version: 1.19.3

When executing macros with `await macro.execute()` with AM installed, the returned value is undefined. Even for the simple case like `return 1;`.
Without AM, execution returns the correct value.

**Comment by WereDev** [comment]
Can confirm.  I'm having the same issue.

**Comment by MrPrimate** [comment]
DDB Importer also experiencing this problem when trying to run macros.

**Comment by mclemente** [comment]
Hey, I've released a update with the fixes proposed by @Cuingamehtar. Tell me if you still run into any issues after updating.

**Comment by MrPrimate** [comment]
Works for me now, thanks!
