### ISSUE TITLE
please remove /amacro requirement

### ISSUE THREAD

**Issue by folken88** [mclemente/fvtt-advanced-macros#59]
before: my blind player types /per to roll a perception check

now: my blind player has to type /amacro per

Might seem like a small change, if you can see. If you can't, it's 6 more opportunities for typos. Please make this a toggle-thing or configurable. This is a huge huge change for people who rely on this function!

**Comment by folken88** [comment]
So the module has this feature now? That was quick! Should I delete this issue or let the dev do so?

**Comment by mclemente** [comment]
I left it open just in case the issue wasn't fixed so you'd have a place to comment on it. I'll close it now.
