### ISSUE TITLE
If we are staying on V10 for a while....

### ISSUE THREAD

**Issue by YenBenGrey** [mclemente/fvtt-advanced-macros#64]
Hello there, 

If we are staying on V10 for a while whilst V11 is being tested, should we refrain from updating Advanced Macros?

**Comment by mclemente** [comment]
Sure, you don't need to update until you move to V11. Advanced Macros 2.0 has a minimum Foundry version of V11, so you shouldn't even be able to update to it while on V10.

**Comment by hedgehog8711** [comment]
Same issue as Yen

![image](https://github.com/mclemente/fvtt-advanced-macros/assets/114251484/19840555-d56b-477b-a666-2ea2652ae9c4)
