### ISSUE TITLE
Failing to understand how to "Run as GM" with a player account

### ISSUE THREAD

**Issue by DarKDinDoN** [mclemente/fvtt-advanced-macros#76]
Hello,

Used this module a long time ago, it changed a lot since then.
Back when I was using it, there was an option "Run as GM" for the players to execute the macro through the GM session.
Can't seem to find this option anymore.

I'm asking this, because I still see some references to this feature in the changelog (recent entries): 
- v2.0.2 -> When the Active GM runs a macro marked as "**Run As GM**" it is now ran immediately instead of being sent to themselves.
- v2.0.1 -> "Fixed an issue when running a macro through sockets (e.g. **as GM**)".
Also, the documentation is a bit lacking, if you don't mind me saying 😸 

Versions:
- Foundry; 11 latest
- AM: latest (2.0.3)

Here is a screenshot of a macro, GM side, with all the options I get:
![image](https://github.com/mclemente/fvtt-advanced-macros/assets/1687854/41cefa44-da23-4053-90d3-0858fc69ab7d)

**Comment by mclemente** [comment]
Hey, the "Run as GM" checkbox has been moved into the "Execute for Specific User" to make the macro window less cluttered. At some point Advanced Macros added 3 settings there and that's when I decided to merge them.

As for your question, you should use the "Game Master" option, it has the same effect as the "Run as GM" option.

Also, your print failed to capture the options. No big deal, I've had this issue myself sometimes.

> Also, the documentation is a bit lacking, if you don't mind me saying 😸

No problem, it is really lacking. With the merge the old tooltip that explained what each option did was removed, and with v2 a lot was changed so I removed a lot of old info on the README and haven't had the time to add new info.

**Comment by DarKDinDoN** [comment]
Thanks for the reply!

Still, one thing I don't understand.
If the "Execute for Specific User" dropdown is only available for non-shared macros (not owned by any players), how is the player supposed to execute it?

**Comment by mclemente** [comment]
Just set the macro's ownership to Observer, the player will be able to run it but not edit it.

**Comment by DarKDinDoN** [comment]
Got it. Thanks.
