### ISSUE TITLE
Executed as gm no longer works in v11

### ISSUE THREAD

**Issue by Nexusprime22** [mclemente/fvtt-advanced-macros#77]
Executed as gm checkbox no longer works in v11
Because there are no features in v11 allowing to accomplish this feature, I was wondering what to do.
Indeed sometimes a player must execute macros that need gm permission
thanks

**Comment by mclemente** [comment]
It seems you've got this issue sorted on the discord https://discord.com/channels/170995199584108546/722566083499786352/1145743215975215155
