### ISSUE TITLE
Put back the run as gm check box

### ISSUE THREAD

**Issue by p4535992** [mclemente/fvtt-advanced-macros#79]
People have some issue to set a macro with "run as gm" option,  they cannot figured out the select option... can you put back the old check box "run as gm" (and automatically get the first gm from the list)

**Comment by Delgored** [comment]
This would be awesome please.

**Comment by mclemente** [comment]
Closing as not planned. The choices are mutually exclusive, so there is no point in having them being separated.

For example, you can't run as a GM and have the select set for a specific player, it will always run as a GM.
