### ISSUE TITLE
Error when installing Advanced Macros 2.0.5 on Foundry v11

### ISSUE THREAD

**Issue by thikness** [mclemente/fvtt-advanced-macros#88]
"Error: module advanced-macros version 2.2.1 requires a more modern version of the Foundry Virtual Tabletop software: 12 or newer"

I get this error when trying to install 2.0.5 from the Foundry v11 module browser. 
 
I was able to install by using this manifest link:
https://github.com/mclemente/fvtt-advanced-macros/releases/download/v2.0.5/module.json

**Comment by mclemente** [comment]
Sorry about that. It should be fixed now.
