### ISSUE TITLE
pf2e broken links

### ISSUE THREAD

**Issue by Tegual** [mclemente/fvtt-advanced-macros#89]
When added to a game with the Pathfinder Second Edition System in V12 (i only noticed it in this version) it breaks the links on the player sheets, under class. This happens if it is the only module as well, after testing with a brand new pf2e system install and a new world with only this module selected.

**Comment by mclemente** [comment]
Can you be more specific on how you reproduce the behavior? Do you mean the links to the class journals inside the class' item?

**Comment by Tegual** [comment]
I added pictures for clarity. Its simple, if i have the advanced macros installed, when i add a class to the character sheet, the link to the class gets broken, if i disable the link works fine.

To replicate, make a new character. Click the hourglass to add a class, then click the 3 dots (...) and click edit item. With advanced macros installed the link to the class is broken, without advanced macros the link works fine.

![not broken](https://github.com/user-attachments/assets/b8e43e2d-5e0c-4949-b5dc-ee4f0da4e801)
![broken](https://github.com/user-attachments/assets/fb838530-4085-4d83-8c31-a1ba315db6db)

**Comment by mclemente** [comment]
I am not having these issues on a new world. Are you on the latest Advanced Macros version (v2.2.1)?
Also, are there any errors on the console?

**Comment by Tegual** [comment]
There where no issues in the console, but manually downloading the repository and overwriting it in the modules seems to have fixed the issue. 

I re-downloaded it from the foundry addons page before i posted the issue so my limited knowledge would tell me maybe something was left behind from a previous version and didn't update properly. Thank you for the help.

**Comment by mclemente** [comment]
Hm, that's odd, but I'm glad everything worked out for you in the end.
